config/routes.rb
Rails.application.routes.draw do :products
  root :to => 'posts#index'
  resources :posts do
    resources :comments, except: [:show, :index]
  end

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  validates :body, :name, :presence => true

end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :title, :presence => true
  validates :body, :presence => true
  has_many :comments
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
  validates_presence_of :username, :presence => true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.

  before_filter :configure_permitted_parameters, if: :devise_controller?

def configure_permitted_parameters
  devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation) }
end

  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
    @post = Post.find(params[:post_id])
    @comment = Comment.new()
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = Comment.create(comment_params)
    if @comment.save
      @post.comments << @comment
      flash[:notice] = "Comment Posted Successfully"
      redirect_to post_path(@post)
    else
      flash[:alert] = "There was a problem. Please fix mistakes or contact support"
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
    @comment = Comment.find(params[:post_id])
  end

  def update
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
    if @comment.update(comment_params)
      @post.comments << @comment
      flash[:notice] = "Comment Posted Successfully"
      redirect_to post_path(@post)
    else
      flash[:alert] = "There was a problem. Please fix mistakes or contact support"
      render :new
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @comment = Comment.find(params[:post_id])
    flash[:notice] = "#{@post.title} successfully deleted."
    @comment.destroy
    redirect_to post_path(@post)
  end

  private

  def comment_params
    params.require(:comment).permit(:name, :body)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all()
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      flash[:notice] = "Successfully posted your post '#{@post.title}'."
      redirect_to posts_path
    else
      render :new
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.new(post_params)
    if @post.save
      flash[:notice] = "Successfully updated #{@post.title}."
      redirect_to posts_path
    else
      render :new
    end
  end

  def destroy
    @post = Post.find(params[:id])
    flash[:notice] = "#{@post.title} successfully deleted."
    @post.destroy
    redirect_to posts_path
  end


  private

  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def create
    
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_form.html.erb
<%= render "layouts/errors", :object => @comment %>

<%= form_for [@post, @comment] do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>
<%= f.label :body %>
<%= f.text_field :body %>
<%= f.submit "comment" %>
<% end %>

app/views/comments/edit.html.erb
<h1> Edit your comment: </h1>

<%= render 'form' %>

app/views/comments/new.html.erb
<h1> Make a New Comment: </h1>

<%= render 'form' %>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
<h3>Please fix these errors:</h3>
<ul>
  <% object.errors.full_messages.each do |message| %>
  <li><%= message %></li>
  <% end %>
</ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blogger</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default">
  <div class="navbar-header">
    <h1><%= link_to "Blogger", "/" %></h1>
    <% if user_signed_in? %>
      Logged in as <strong><%= current_user.email %></strong>.
      <%= link_to 'Edit profile', edit_user_registration_path %> |
      <%= link_to "Logout", destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to "Sign up", new_user_registration_path %> |
      <%= link_to "Login", new_user_session_path %>
    <% end %>
  </div>
</nav>

<font color="red"><%= flash[:alert] %></font>
<font color="green"><%= flash[:notice] %></font>

<div class="container">
  <div class="jumbotron">
    <%= yield %>
  </div>
</div>

</body>
</html>

app/views/posts/_form.html.erb
<%= render "layouts/errors", :object => @post %>

<%= form_for @post do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :body %>
  <%= f.text_field :body %>
  <%= f.submit "post" %>
<% end %>

app/views/posts/edit.html.erb
<%= render 'form' %>

app/views/posts/index.html.erb
<h1> All Posts </h1>

<table>
  <% @posts.each do |post| %>
    <tr>
      <td><%= link_to post.title, post_path(post) %></td>
      <td><%= post.created_at.to_date %></td>
    </tr>
  <% end %>
</table>
<br>
<%= link_to "Create New Post", new_post_path %>

app/views/posts/show.html.erb
<h1> <%= @post.title %> </h1>

<br>

<p> <%= @post.body %> </p>

<%= link_to "Edit", edit_post_path %>
<br>
<%= link_to "Delete", post_path(@post), :data => {:confirm => "Are you sure?", :method => "delete"} %>
<br>

<%= link_to "Comment", new_post_comment_path(@post) %>

<ul>
  <% @post.comments.each do |comment| %>

  <li> <%= comment.name %> said "<%= comment.body %>" at <%= comment.created_at.to_time %>
        <%= link_to "Edit Comment", edit_post_comment_path(comment, @post) %>
        <%= link_to "Delete Comment", post_comment_path(comment, @post), :data => {:confirm => "Are you sure?", :method => "delete"} %>
        </li>

  <% end %>
</ul>